Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "apple")
Ingredient.create(name: "orange")
Ingredient.create(name: "coconut")
Ingredient.create(name: "olives")

Cocktail.create(name: "White Russian")
Cocktail.create(name: "Moscow Mule")
